### ISSUE TITLE
Summary endpoint

### ISSUE THREAD

**Issue by NathanMaton** [joshwallerr/docdecoder#14]
How are you using the LLMs to summarize the content. I saw there's a call to 'https://docdecoder.app/summarize' on your docdecoder site in the summarizeDocument function in background.js. 

Are you considering open-sourcing that code, too?

**Comment by joshwallerr** [comment]
Yes good idea, I'll add a few of the Flask endpoints to a file in this repo so you can see prompts, how summaries are handled etc.
